import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Página dos usuários',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="h-[80px] flex items-center p-6 border-b-[1px] border-b-slate-100">
          Esse é um header
        </header>
        <main className="p-6">{children}</main>
      </body>
    </html>
  );
}
